/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ProjetoTeste;

import org.junit.Test;

import ProjetoTeste.model.Calculadora;

import static org.junit.Assert.assertEquals;
import org.junit.Before;


public class CalculadoraTest {
	
	private Calculadora calculadora;
	
	@Before
	public void setUp() throws Exception {
		calculadora = new Calculadora();
	}
	
	@Test
	public void testaSomaValorPositivo() {
		assertEquals("", 7, calculadora.soma(4, 3));
	}
	
	@Test
	public void testaSomaNegativo() {
		assertEquals("", -10, calculadora.soma(-15, 5));
	}
	
	@Test
	public void testasubtracaoPositivo() {
		assertEquals("", 11, calculadora.subtracao(16, 5));
	}
	
	@Test
	public void testasubtracaoNegativo() {
		assertEquals("", -6, calculadora.subtracao(5, 11));
	}
	
	@Test
	public void testamultiplicacaoPositivo() {
		assertEquals("", 10, calculadora.multiplicacao(5, 2));
	}
	
	@Test
	public void testamultiplicacaoNegativo() {
		assertEquals("", 16, calculadora.multiplicacao(-8, -2));
	}
	
	@Test
	public void testardivisaopositivo() {
		assertEquals("", 10, calculadora.divisao(20, 2));
	}
	
	@Test
	public void testardivisaoNegativo() {
		assertEquals("", -25, calculadora.divisao(-50, 2));
	}
}
