/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ProjetoTeste.model;

public class Calculadora {
   
	public int soma(int a, int b) {
		return a+b;
	}
	
	public int subtracao(int a, int b) {
		return a-b;
	}
	
	public int multiplicacao(int a, int b) {
		return a*b;
	}
	
	public int divisao(int a, int b) {
		return a/b;
	}
}

